#!/usr/bin/python3
import sys


f = open(sys.argv[1])
for line in f:
    ans = 1
    num = int(line)
    if num % 2 == 0:
        print("{:d}={:d}*2".format(num, num // 2))
    for i in range(2, num // 2 + 1):
        if num % i == 0:
            ans = num // i
            break
    print("{:d}={:d}*{:d}".format(num, ans, num // ans))
